### ISSUE TITLE
Please fix AUTH_TOKEN validation for HTTP mode (docker production stack)

### ISSUE THREAD

**Issue by naXa777** [czlonkowski/n8n-mcp#16]
container boot logs:

```
n8n-mcp-1  | ERROR: AUTH_TOKEN is required for HTTP mode
```

I do not specify `AUTH_TOKEN` variable. I use `AUTH_TOKEN_FILE` instead, like recommended in the [Example Production Stack](https://github.com/czlonkowski/n8n-mcp/blob/main/docs/DOCKER_README.md#example-production-stack).
```
# ...
    environment:
      MCP_MODE: http
      AUTH_TOKEN_FILE: /run/secrets/auth_token
      NODE_ENV: production
#... 

secrets:
  auth_token:
    file: ./secrets/auth_token.txt
```

**Comment by czlonkowski** [comment]
Fixed in v2.7.5\! 🎉

The AUTH_TOKEN_FILE support has been implemented. The HTTP server now:
- Checks AUTH_TOKEN environment variable first
- Falls back to reading from AUTH_TOKEN_FILE if AUTH_TOKEN is not set
- Properly handles Docker secrets pattern
- Includes error handling for missing/unreadable files

Thank you for reporting this issue\!

**Comment by naXa777** [comment]
I’ve pulled the latest image and tested it, but unfortunately the issue persists.

Container log:
```
n8n-mcp-1  | ERROR: AUTH_TOKEN is required for HTTP mode
n8n-mcp-1  | ERROR: AUTH_TOKEN is required for HTTP mode
n8n-mcp-1  | ERROR: AUTH_TOKEN is required for HTTP mode
n8n-mcp-1  | ERROR: AUTH_TOKEN is required for HTTP mode
n8n-mcp-1  | ERROR: AUTH_TOKEN is required for HTTP mode
n8n-mcp-1 exited with code 1
```

My docker-compose.yml (relevant parts):
```
n8n-mcp:
  image: ghcr.io/czlonkowski/n8n-mcp:latest
  ports:
    - "6789:6789"
  restart: always
  environment:
    MCP_MODE: http
    USE_FIXED_HTTP: true
    AUTH_TOKEN_FILE: /run/secrets/auth_token
    NODE_ENV: production
    PORT: 6789
    N8N_API_URL: http://n8n:5678
    N8N_API_KEY: ${N8N_API_KEY}
    TRUST_PROXY: "1"
    GENERIC_TIMEZONE: Europe/Berlin
    TZ: Europe/Berlin
    LOG_LEVEL: debug
  secrets:
    - auth_token

secrets:
  auth_token:
    file: .auth_token.txt
```

✅ The secret file .auth_token.txt is present.

It looks like `AUTH_TOKEN_FILE` is still not picked up.
@czlonkowski, could you please reopen the issue and advise how I can help debug further?

Thanks again for your work!

**Comment by naXa777** [comment]
FYI: the server starts after I replace `AUTH_TOKEN_FILE` with `AUTH_TOKEN`. container logs:

```
n8n-mcp-1  | Starting n8n Documentation MCP Server in http mode...
n8n-mcp-1  | Current directory: /app
n8n-mcp-1  | Node version: v20.19.3
n8n-mcp-1  | [2025-07-06T20:34:24.259Z] [n8n-mcp] [INFO] Using AUTH_TOKEN from environment variable
n8n-mcp-1  | [2025-07-06T20:34:24.267Z] [n8n-mcp] [INFO] Trust proxy enabled with 1 hop(s)
n8n-mcp-1  | [2025-07-06T20:34:24.270Z] [n8n-mcp] [INFO] Node.js version: v20.19.3
n8n-mcp-1  | [2025-07-06T20:34:24.270Z] [n8n-mcp] [INFO] Platform: linux arm64
n8n-mcp-1  | [2025-07-06T20:34:24.270Z] [n8n-mcp] [INFO] Attempting to use better-sqlite3...
n8n-mcp-1  | [2025-07-06T20:34:24.344Z] [n8n-mcp] [INFO] Initializing n8n Documentation MCP server
n8n-mcp-1  | [2025-07-06T20:34:24.347Z] [n8n-mcp] [INFO] MCP server initialized with 39 tools (n8n API: configured)
n8n-mcp-1  | [2025-07-06T20:34:24.347Z] [n8n-mcp] [INFO] Created persistent MCP server instance
n8n-mcp-1  | [2025-07-06T20:34:24.356Z] [n8n-mcp] [INFO] Successfully initialized better-sqlite3 adapter
n8n-mcp-1  | [2025-07-06T20:34:24.356Z] [n8n-mcp] [INFO] Initialized database from: /app/data/nodes.db
n8n-mcp-1  | [2025-07-06T20:34:24.359Z] [n8n-mcp] [INFO] n8n MCP Fixed HTTP Server started { port: 6789, host: '0.0.0.0' }
n8n-mcp-1  | n8n MCP Fixed HTTP Server running on 0.0.0.0:6789
n8n-mcp-1  | Health check: http://localhost:6789/health
n8n-mcp-1  | MCP endpoint: http://localhost:6789/mcp
n8n-mcp-1  | 
n8n-mcp-1  | Press Ctrl+C to stop the server
```

**Comment by czlonkowski** [comment]
I will look into that @naXa777

**Comment by czlonkowski** [comment]
Hi @naXa777 ,

Great news\! This is now fully fixed in v2.7.10 🎉

The issue was that the Docker entrypoint script was only checking for `AUTH_TOKEN` but not `AUTH_TOKEN_FILE`. I've updated both the entrypoint and the application code to properly support Docker secrets.

Your docker-compose configuration should now work exactly as you had it:

```yaml
environment:
  MCP_MODE: http
  AUTH_TOKEN_FILE: /run/secrets/auth_token
  NODE_ENV: production

secrets:
  auth_token:
    file: ./secrets/auth_token.txt
```

The fix includes:
- Docker entrypoint now accepts either `AUTH_TOKEN` or `AUTH_TOKEN_FILE`
- Both HTTP server implementations support file-based tokens
- Added validation to ensure the token file exists
- Tokens are trimmed to handle any whitespace issues

Please pull the latest image and let me know if everything works as expected. Thanks for your patience and for using Docker secrets - it's definitely the more secure approach\! 🔒

**Comment by naXa777** [comment]
I confirm that the fix works. Thank you!

```
n8n-mcp-1  | [2025-07-08T11:51:00.725Z] [n8n-mcp] [INFO] Loaded AUTH_TOKEN from file: /run/secrets/auth_token
```
